version: '3.9'

services:
  app:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    env_file:
      - .env  # Load environment variables from .env
    depends_on:
      - mongo
    volumes:
      - .:/app  # Mount the current directory to the /app directory inside the container
    networks:
      - fastapi-network

  mongo:
    image: mongo:6.0
    container_name: fastapi_mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    networks:
      - fastapi-network

networks:
  fastapi-network:
    driver: bridge
